# Generated by Django 5.0.2 on 2024-02-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_postcomment_userfollow_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=84, null=True),
        ),
    ]
