# Generated by Django 5.0.2 on 2024-02-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_pdfs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
