# Generated by Django 5.0.2 on 2024-04-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('jobType', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
    ]
